name: Release

on: workflow_dispatch

jobs:
    release:
        permissions: 
            contents: read
            id-token: write
        env:
            NODE_AUTH_TOKEN: ""   
            NPM_TOKEN: ""
        strategy:
            fail-fast: false
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 24
                  registry-url: 'https://registry.npmjs.org'

            - uses: pnpm/action-setup@v3
              name: Install pnpm
              id: pnpm-install
              with:
                  version: '9'
                  run_install: false

            - name: Get pnpm store directory
              id: pnpm-cache
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

            - uses: actions/cache@v4
              name: Setup pnpm cache
              with:
                  path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Lint
              run: pnpm lint

            - name: Build
              run: |
                  pnpm build

            - name: Pack
              shell: bash
              run: |
                  npm run pack

            - name: Run @arethetypeswrong/cli
              run: |
                  pnpm attw package.tgz

            - name: Remove temp npmrc
              run: rm -f "$NPM_CONFIG_USERCONFIG"

            - name: Update NPM
              run: npm install -g npm@latest

            - name: Extract package info
              id: pkg
              run: |
                NAME=$(node -p "require('./package.json').name")
                VERSION=$(node -p "require('./package.json').version")
                echo "name=$NAME" >> $GITHUB_OUTPUT
                echo "version=$VERSION" >> $GITHUB_OUTPUT

            - name: Check for NPM version existence
              id: npm_check
              run: |
                if npm view "${{ steps.pkg.outputs.name }}@${{ steps.pkg.outputs.version }}" version > /dev/null 2>&1; then
                  echo "exists=true" >> $GITHUB_OUTPUT
                else
                  echo "exists=false" >> $GITHUB_OUTPUT
                fi

            - name: Check for GitHub version existence
              id: gpr_check
              env:
                NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                echo "@${{ github.repository_owner }}:registry=https://npm.pkg.github.com" > ~/.npmrc
                echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" >> ~/.npmrc

                if npm view "${{ steps.pkg.outputs.name }}@${{ steps.pkg.outputs.version }}" version --registry=https://npm.pkg.github.com > /dev/null 2>&1; then
                  echo "exists=true" >> $GITHUB_OUTPUT
                else
                  echo "exists=false" >> $GITHUB_OUTPUT
                fi

            - name: Publish to NPM
              if: steps.npm_check.outputs.exists == 'false'
              shell: bash
              run: |
                  echo "Publishing ${{ steps.pkg.outputs.name }}@${{ steps.pkg.outputs.version }}"
                  npm publish package.tgz --provenance

                  echo "npm: \`+ ${{ steps.pkg.outputs.name }}@${{ steps.pkg.outputs.version }}\`" >> $GITHUB_STEP_SUMMARY

            - name: Skip publish to NPM
              if: steps.npm_check.outputs.exists == 'true'
              run: echo "npm version already exists, skipping"

            - name: Setup npm for GitHub Packages
              if: steps.gpr_check.outputs.exists == 'false'
              run: |
                echo "@${{ github.repository_owner }}:registry=https://npm.pkg.github.com" > ~/.npmrc
                echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" >> ~/.npmrc
              env:
                NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Publish to GitHub Packages
              if: steps.gpr_check.outputs.exists == 'false'
              run: npm publish package.tgz --access public
              env:
                NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Skip publishing to GitHub
              if: steps.gpr_check.outputs.exists == 'true'
              run: echo "GitHub Packages version already exists, skipping"